# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1

# Issues with these labels will never be considered stale
exemptLabels:
#  - pinned
#  - security

# Label to use when marking an issue as stale
staleLabel: expirada

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Esta vaga foi marcada automaticamente como obsoleta porque não teve atividade recente. Será fechado se nenhuma atividade adicional ocorrer.

  This job opening has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
